# Generated by Django 6.0.5 on 2026-05-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_affiliate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10),
        ),
    ]
